### ISSUE TITLE
Define DAQ Interface

### ISSUE THREAD

**Issue by tknopp** [MagneticParticleImaging/MPIMeasurements.jl#20] opened 2021-03-25 19:58 UTC
The Interface of `AbstractDAQ` is currently not well defined and the RedPitaya implementation is certainly leaking too much implementation details. This needs to be sorted out. This issue is for summarizing ideas around this.

**Comment by jonschumacher** [comment] 2021-04-16 16:54
From my perspective, the params dict pretty much replicates the MDF. If we just require a function `startTx(scanner, mdf)` with a given MDF file with the parameters from the acquisition group filled and then a function `readFrames(scanner, mdf, isBackground)` we should be fine, shouldn’t we? This also avoids replicating stuff from MPIFiles.

**Comment by tknopp** [comment] 2021-04-16 21:36
So yes the params dict replicates the MDF which is quite nice since it helps us directly storing the measurement data into an MDF. Regarding your example its is not clear what the `mdf` is. Currently an `MDF` has no in-memory representation (i.e. a proper type) but we read MDF data on demand. If `mdf` is really meant to be a file I kind of see an egg and a chicken problem. One then first needs to generate an MDF before making the measurement. This is IMHO not  really a good interface. In particular it will be not so nice when performing measurements that are never stored in a file (i.e. online measurements). That would require building some dummy measurement. And actually in order to generate an MDF one right now would need a parameter dict anyway.

**Comment by jonschumacher** [comment] 2021-04-17 05:26
Yes, I thought about just using a scratch MDF file but I get the point about the online measurement which might live in some network storage. But in principle you agree that the MDF `acquisition ` group is all we need? Would it then make sense to create a MDF representation (maybe using Configurations.jl) and have methods to convert between the duct, the file and the representation? We could then forward all methods working on an MDFFile to the representation which would also give us the benefit of being typed correctly. A possible name could be MDFInMemory.

**Comment by tknopp** [comment] 2021-04-17 08:00
* I agree that using types / structs instead of dicts can be better in the long run. There is also a performance issue with dicts since the type information is not preserved. For this reason I actually introduced the DAQ params: https://github.com/MagneticParticleImaging/MPIMeasurements.jl/blob/master/src/DAQ/Parameters.jl
* If the MDF/acquisition is sufficient is not so clear to me. For calibration scans certainly also the calibration group is required. But I agree that MDF/acquisition is the core of it
* If I get it right you are mostly struggling with that I mix up acquisition parameters and hardware parameters in the DAQ section of the TOML. I 100% agree that this is not good and that we should better structure this.
* In my opinion we should make improve the `Sequence` and make it control all SeFo but also the drive field parameters. Or is your take that we should unify the sequence infrastructure and the `MDF/acquisition` object you were talking about above.

I am pinging @hofmannmartin since he has been working on actually the same topic in the context of `MPISimulations`. There the idea was also to use TOML files for describing sequence parameters and so on. Makes sense to unify the thought and move the infrastructure to `MPIFiles` and not `MPIMeasurements`.

**Comment by jonschumacher** [comment] 2021-04-19 08:44
- _I agree that using types / structs instead of dicts can be better in the long run. There is also a performance issue with dicts since the type information is not preserved. For this reason I actually introduced the DAQ params: https://github.com/MagneticParticleImaging/MPIMeasurements.jl/blob/master/src/DAQ/Parameters.jl_
I will make a pull request for MPIFiles with a proposal for a struct. I think this is better placed in there since it is strongly linked to the MDF. After the MDFInMemory is filled it can be converted to an MDFFile after applying checks on the data consistency.
- _If the MDF/acquisition is sufficient is not so clear to me. For calibration scans certainly also the calibration group is required. But I agree that MDF/acquisition is the core of it_
It sounds like we really need a definition of sequences and protocols first. A calibration procedure definitely fits into a protocol scheme.
- _If I get it right you are mostly struggling with that I mix up acquisition parameters and hardware parameters in the DAQ section of the TOML. I 100% agree that this is not good and that we should better structure this._
Yes, thats my main concern. I will come up with an extended proposal for the hardware definition and then we can see if that split can be done nicely.
- _In my opinion we should make improve the Sequence and make it control all SeFo but also the drive field parameters. Or is your take that we should unify the sequence infrastructure and the MDF/acquisition object you were talking about above._
See above.
- _I am pinging @hofmannmartin since he has been working on actually the same topic in the context of MPISimulations. There the idea was also to use TOML files for describing sequence parameters and so on. Makes sense to unify the thought and move the infrastructure to MPIFiles and not MPIMeasurements._
Do you think it fits in the scope of MPIFiles or should we have a package MPIProtocols with definitions for sequences and protocols? This can be shared between MPISimulations and MPIMeasurements and can also provide tools for creating protocols and sequences.

**Comment by tknopp** [comment] 2021-04-19 10:22
* *I will make a pull request for MPIFiles with a proposal for a struct. I think this is better placed in there since it is strongly linked to the MDF.*  
I agree 100%.

* Do you think it fits in the scope of MPIFiles or should we have a package MPIProtocols with definitions for sequences and protocols?
I think it fits into the scope of MPIFiles. We can split things off later if we need to. Best is to put things into dedicated folders and then one can move things around (if needed). MPIFiles right now already has a little bit larger scope since it should provide the base infrastructure for everything else. So having things there MPIMeasurements and MPISimulations can nicely share infrastructure.  (Side note: In Julia one can nowadays also have multiple packages within a single Git repository, see https://github.com/timholy/SnoopCompile.jl  This can have advantages when wanting to structure out smaller things without the need to make dedicated repositories, which have a higher maintenance cost. This is nothing we need to do right now but just wanted to point this out.)

**Comment by hofmannmartin** [comment] 2021-04-20 08:52
In the context of `MPISimulations` It would really great split between acquisition parameters and the hardware setup. This would be similar with an actual measurement, where an acquisition parameter describing a 12 mT excitation does not necessarily mean that a 12 mT excitation field was actually present in the hardware.I see the acquisition parameters more as a way to achieve reproducibility. Such that if I put the same parameters into the same hardware, I get the same excitation.

What is missing is maybe a generalized and unified way to describe a hardware setup. At least from the simulation point of view.

**Comment by jonschumacher** [comment] 2021-05-19 11:10
With a clear definition of a sequence as proposed in #22 we should also have a clear interface for the DAQ, at least from my perspective. This means that resolving https://github.com/MagneticParticleImaging/MPIFiles.jl/issues/37 also resolves this issue at least partially. The DAQ should then accept all electrial transmit channels and set up this part of a sequence on its own. The receive side should also work with the current definition of a sequence.
Am I missing something here?

**Closed** 2021-12-03 12:21 UTC
